default_install_hook_types: ["pre-push"]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format

  # docformatter - formats docstrings to follow PEP 257
  - repo: https://github.com/pycqa/docformatter
    # todo: replace when >v1.7.5 will be published
    rev: 06907d0267368b49b9180eed423fae5697c1e909
    hooks:
      - id: docformatter
        name: docformatter
        args:
          [
            -r,
            -i,
            --pre-summary-newline,
            --make-summary-multi-line,
            --wrap-summaries,
            "90",
            --wrap-descriptions,
            "90",
            "boussole",
          ]

  - repo: local
    hooks:
      - id: pylint
        name: Run Pylint
        entry: "pylint"
        args: ["./boussole/*"]
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: make
        args: ["test"]
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: ^.*\.(py|c|h|md|rst|yml)$
