# Those variables are for testing
CMD =
UVCMD = uv run
PIPELINE_PROW=pipeline-prow.yaml
GH_REPO_OWNER = chmouel
GH_REPO_NAME = scratchmyback
GH_PR_NUM = 345
GH_PR_SENDER = chmouel
PASS_TOKEN = github/chmouel-token
PRURL = https://github.com/$(GH_REPO_OWNER)/$(GH_REPO_NAME)/pull/$(GH_PR_NUM)

generate:
	@echo "Generating $(PIPELINE_PROW) 🚿" && \
		echo "####### Do not edit this file use make generate" > $(PIPELINE_PROW) && \
		$(UVCMD) ./hack/tekton-task-embed-script.py prow/base.yaml >> $(PIPELINE_PROW)

test:
	@ [[ -n "$(CMD)" ]] || (echo "Please specify a command to run as argument: like make test CMD=/lgtm" && exit 1)
	@env GH_PR_NUM=$(GH_PR_NUM) GH_REPO_NAME=$(GH_REPO_NAME) GH_REPO_OWNER=$(GH_REPO_OWNER) \
		GH_PR_SENDER=$(GH_PR_SENDER) \
		PAC_TRIGGER_COMMENT="$(CMD)" GITHUB_TOKEN=`pass show $(PASS_TOKEN)` \
		./prow/prow.py

open_pr:
	@if type -p xdg-open; then xdg-open $(PRURL); elif type -p open ;then open $(PRURL);fi

check:
	@tmpfile=`mktemp /tmp/check-XXXXXX`; \
		make -s generate PIPELINE_PROW=$${tmpfile} && \
		if ! cmp -s $(PIPELINE_PROW) $$tmpfile; then \
		echo "Changes is needed: make sure to modify the prun in prow/ and run make generate before pushing"; \
			diff --color=always -u $(PIPELINE_PROW) $$tmpfile; \
			rm -f $$tmpfile; \
			exit 1; \
		fi ; \
		rm -f $$tmpfile; \
