[project]
name = "pipelines-as-code-prow"
version = "0.1.0"
description = "Pipelines as Code prow let you interact with tekton pipelines via Gitops command a la prow."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "pre-commit>=4.1.0",
    "pylint>=3.3.4",
    "pytest",
]
