---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: prow-commands
  annotations:
    pipelinesascode.tekton.dev/on-comment: |
      ^/(help|lgtm|(assign|unassign|label|unlabel)[ ].*)$
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_owner
    - name: repo_name
    - name: pull_request_number
    - name: pull_request_sender
    - name: git_auth_secret
    - name: git_auth_secret_key
      default: git-provider-token
    - name: trigger_comment
    - name: lgtm_treshold
      default: "1"
  tasks:
    - name: manage-pr
      displayName: Manage PR Assignments & Labels
      taskSpec:
        steps:
          - name: manage-pr
            image: registry.access.redhat.com/ubi9/ubi
            env:
              - name: GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: "$(params.git_auth_secret)"
                    key: "$(params.git_auth_secret_key)"
              - name: GH_REPO_OWNER
                value: "$(params.repo_owner)"
              - name: GH_PR_SENDER
                value: "$(params.pull_request_sender)"
              - name: GH_REPO_NAME
                value: "$(params.repo_name)"
              - name: GH_PR_NUM
                value: "$(params.pull_request_number)"
              - name: PAC_TRIGGER_COMMENT
                value: |
                  $(params.trigger_comment)
              - name: PAC_LGTM_TRESHOLD
                value: "$(params.lgtm_treshold)"
            script: |
              #include prow.py
