---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: linters
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
spec:
  params:
    - name: repo_url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
  pipelineSpec:
    tasks:
      - name: linters
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: fetch-repo
              ref:
                resolver: http
                params:
                  - name: url
                    value: https://raw.githubusercontent.com/tektoncd/catalog/main/stepaction/git-clone/0.1/git-clone.yaml
              params:
                - name: output-path
                  value: $(workspaces.source.path)
                - name: url
                  value: "$(params.repo_url)"
                - name: revision
                  value: "$(params.revision)"

            - name: pre-commit
              image: registry.access.redhat.com/ubi9/go-toolset
              workingDir: $(workspaces.source.path)
              script: |
                git config --global --add safe.directory $(workspaces.source.path)
                curl -LsSf https://astral.sh/uv/install.sh | sh
                source $HOME/.local/bin/env
                uv sync --group=dev
                source .venv/bin/activate
                pre-commit run --all-files
            - name: markdownlint
              displayName: "Markdown Linter"
              image: thegeeklab/markdownlint-cli
              workingDir: $(workspaces.source.path)
              script: |
                markdownlint README.md
    workspaces:
      - name: source
  workspaces:
    - name: source
      emptyDir: {}
